/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/topics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 주제 목록
         * @description sortOrder 오름차순, 같으면 이름순. 미분류 노트 수를 함께 준다.
         */
        get: operations["listTopics"];
        put?: never;
        /** 주제 생성 */
        post: operations["createTopic"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/topics/{topicId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 주제 삭제
         * @description 소속 노트는 지우지 않고 미분류로 옮긴다.
         *     미분류에 같은 제목의 노트가 이미 있으면 삭제하지 않고 409 NOTE_TITLE_TAKEN을 돌려준다.
         *     error.details.titles에 겹치는 제목 목록이 들어 있다. 사용자가 제목을 바꾼 뒤 다시 시도한다.
         */
        delete: operations["deleteTopic"];
        options?: never;
        head?: never;
        /**
         * 주제 이름·표시 순서 변경
         * @description 보낸 필드만 바꾼다.
         */
        patch: operations["updateTopic"];
        trace?: never;
    };
    "/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 노트 목록·검색
         * @description 본문은 주지 않는다. 사이드바와 검색 결과용.
         */
        get: operations["listNotes"];
        put?: never;
        /** 노트 생성 */
        post: operations["createNote"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{noteId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        /** 노트 한 건 (본문 포함) */
        get: operations["getNote"];
        /**
         * 노트 제목·본문 수정
         * @description 요청의 version이 서버 값과 다르면 그 사이에 다른 곳에서 고친 것이므로 409 NOTE_CONFLICT를 돌려준다.
         *     error.details.current에 서버의 현재 노트가 들어 있다. 성공하면 version이 1 늘어난다.
         *     충돌 창에서 "내 내용으로 덮어쓰기"를 고르면 앱은 같은 제목·본문을 details.current.version으로 다시 보낸다.
         *     "다른 곳의 내용 불러오기"를 고르면 details.current를 편집기에 채운다.
         */
        put: operations["updateNote"];
        post?: never;
        /** 노트 삭제 */
        delete: operations["deleteNote"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notes/{noteId}/topic": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * 노트를 다른 주제로 이동
         * @description topicId가 null이면 미분류로 옮긴다. 제목·본문과 version은 바뀌지 않는다.
         *     옮길 주제에 같은 제목이 있으면 409 NOTE_TITLE_TAKEN.
         */
        put: operations["moveNote"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Topic: {
            /** Format: uuid */
            id: string;
            name: string;
            sortOrder: number;
            noteCount: number;
            /** Format: date-time */
            createdAt: string;
        };
        TopicList: {
            topics: components["schemas"]["Topic"][];
            unassignedNoteCount: number;
        };
        TopicCreate: {
            name: string;
        };
        TopicUpdate: {
            name?: string;
            sortOrder?: number;
        };
        Note: {
            /** Format: uuid */
            id: string;
            /**
             * Format: uuid
             * @description null이면 미분류
             */
            topicId: string | null;
            title: string;
            /** @description 마크다운 원문 (NFC) */
            body: string;
            /** @description 제목·본문을 수정할 때마다 1 증가 */
            version: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NoteSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            topicId: string | null;
            title: string;
            /** @description 검색어가 있으면 본문에서 검색어 주변 80자, 없으면 본문 앞 80자 */
            snippet: string;
            /** Format: date-time */
            updatedAt: string;
        };
        NoteCreate: {
            title: string;
            /**
             * Format: uuid
             * @default null
             */
            topicId?: string | null;
            /** @default  */
            body?: string;
        };
        NoteUpdate: {
            title: string;
            body: string;
            /** @description 편집을 시작할 때 받은 version */
            version: number;
        };
        Error: {
            error: {
                /** @enum {string} */
                code: "VALIDATION_FAILED" | "NOT_FOUND" | "TOPIC_NAME_TAKEN" | "NOTE_TITLE_TAKEN" | "NOTE_CONFLICT" | "INTERNAL";
                /** @description 사용자에게 보여줄 수 있는 한국어 문장 */
                message: string;
                /**
                 * @description VALIDATION_FAILED - fields: [{field, reason}]
                 *     NOTE_TITLE_TAKEN  - titles: [겹치는 제목]
                 *     NOTE_CONFLICT     - current: Note
                 */
                details?: {
                    [key: string]: unknown;
                };
            };
        };
    };
    responses: {
        /** @description 필수 필드 누락, 길이 초과, '/' 포함 등 */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "VALIDATION_FAILED",
                 *         "message": "제목에는 '/'를 쓸 수 없습니다.",
                 *         "details": {
                 *           "fields": [
                 *             {
                 *               "field": "title",
                 *               "reason": "contains_slash"
                 *             }
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 없는 id */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 같은 이름의 주제가 이미 있음 */
        TopicNameTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 같은 주제(또는 미분류)에 같은 제목이 이미 있음 */
        NoteTitleTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOTE_TITLE_TAKEN",
                 *         "message": "미분류에 같은 제목의 노트가 있어 주제를 삭제할 수 없습니다.",
                 *         "details": {
                 *           "titles": [
                 *             "인덱스"
                 *           ]
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        TopicId: string;
        NoteId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listTopics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TopicList"];
                };
            };
        };
    };
    createTopic: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicCreate"];
            };
        };
        responses: {
            /** @description 생성됨. sortOrder는 기존 최댓값 + 1 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            409: components["responses"]["TopicNameTaken"];
        };
    };
    deleteTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoteTitleTaken"];
        };
    };
    updateTopic: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                topicId: components["parameters"]["TopicId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TopicUpdate"];
            };
        };
        responses: {
            /** @description 변경됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Topic"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["TopicNameTaken"];
        };
    };
    listNotes: {
        parameters: {
            query?: {
                /** @description 주제 id. 'none'이면 미분류만. 없으면 전체. */
                topicId?: string;
                /** @description 제목 또는 본문에 들어간 문자열 (대소문자 무시, 부분 일치) */
                q?: string;
                sort?: "title" | "updated";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        notes: components["schemas"]["NoteSummary"][];
                    };
                };
            };
            400: components["responses"]["ValidationFailed"];
        };
    };
    createNote: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "title": "재시도 정책",
                 *       "topicId": "5b20c1d4-8f2a-4e61-9b3a-2d7f0c9e1a44",
                 *       "body": "# 재시도 정책\n- 응답 타임아웃이 발생하면 클라이언트는 같은 요청을 다시 보낸다."
                 *     }
                 */
                "application/json": components["schemas"]["NoteCreate"];
            };
        };
        responses: {
            /** @description 생성됨. version은 0 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoteTitleTaken"];
        };
    };
    getNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 성공 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteUpdate"];
            };
        };
        responses: {
            /** @description 수정됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            400: components["responses"]["ValidationFailed"];
            404: components["responses"]["NotFound"];
            /** @description NOTE_CONFLICT (version 불일치) 또는 NOTE_TITLE_TAKEN (같은 주제에 같은 제목) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    deleteNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 삭제됨 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["NotFound"];
        };
    };
    moveNote: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                noteId: components["parameters"]["NoteId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    topicId: string | null;
                };
            };
        };
        responses: {
            /** @description 이동됨 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Note"];
                };
            };
            404: components["responses"]["NotFound"];
            409: components["responses"]["NoteTitleTaken"];
        };
    };
}
